DROP TABLE IF EXISTS action_required
DROP TABLE IF EXISTS review
DROP TABLE IF EXISTS plans
DROP TABLE IF EXISTS stage
DROP TABLE IF EXISTS cost_list
DROP TABLE IF EXISTS activity_resource
DROP TABLE IF EXISTS resource_given
DROP TABLE IF EXISTS groups_involved
DROP TABLE IF EXISTS activity
DROP TABLE IF EXISTS staff_role
DROP TABLE IF EXISTS roles
DROP TABLE IF EXISTS staff



 